#!/usr/bin/env bash
# init-config.sh — create or update config.env (interactive or from env vars).
#
# Non-interactive (e.g. Agent passes values):
#   TS_ZONE=example.com TS_SUBDOMAIN=share TS_TUNNEL_NAME=share bash scripts/init-config.sh
#
# Interactive:
#   bash scripts/init-config.sh
set -euo pipefail
source "$(dirname "$0")/lib.sh"

OUT="$TS_CONFIG_FILE"
EXAMPLE="$TS_SKILL_DIR/config.env.example"

prompt() {
  local var="$1" label="$2" default="${3:-}" hint="${4:-}"
  local val
  if [ -n "${!var:-}" ]; then
    return 0
  fi
  if [ ! -t 0 ]; then
    ts_die "缺少 $var；非交互模式请通过环境变量传入，例如: TS_ZONE=example.com bash scripts/init-config.sh"
  fi
  echo "$hint" >&2
  if [ -n "$default" ]; then
    read -r -p "$label [$default]: " val
    val="${val:-$default}"
  else
    read -r -p "$label: " val
  fi
  printf -v "$var" '%s' "$val"
}

validate_name() {
  local label="$1" val="$2"
  if ! printf '%s' "$val" | grep -Eq '^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$'; then
    ts_die "$label 格式无效（字母数字与连字符，1-63 字符）: $val"
  fi
}

validate_zone() {
  local z="$1"
  if ! printf '%s' "$z" | grep -Eq '^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$'; then
    ts_die "TS_ZONE 格式无效（示例: example.com）: $z"
  fi
}

echo "═══ tunnel-serve 配置 ═══"
echo

if [ -f "$OUT" ]; then
  echo "· 将更新现有 $OUT"
  set -a
  # shellcheck disable=SC1090
  source "$OUT"
  set +a
else
  echo "· 将创建 ${OUT} (参考 ${EXAMPLE})"
fi
echo

# --- Collect required vars -------------------------------------------------
prompt TS_ZONE "Cloudflare 根域名 (TS_ZONE)" "" \
  "须已在 Cloudflare 托管。Dashboard → 网站 → 添加站点。"

prompt TS_SUBDOMAIN "子域名 (TS_SUBDOMAIN)" "share" \
  "公网地址为 https://<子域名>.<根域名>/<路径>/"

prompt TS_TUNNEL_NAME "隧道名称 (TS_TUNNEL_NAME)" "${TS_SUBDOMAIN:-share}" \
  "cloudflared 账户内唯一名称；可与子域名相同。"

[ -n "${TS_PORT:-}" ] || TS_PORT="8787"
if [ -t 0 ]; then
  read -r -p "本地端口 (TS_PORT) [$TS_PORT]: " _port
  TS_PORT="${_port:-$TS_PORT}"
fi

[ -n "${TS_DEFAULT_TTL:-}" ] || TS_DEFAULT_TTL="3600"
if [ -t 0 ]; then
  read -r -p "默认自动关闭秒数 (TS_DEFAULT_TTL) [$TS_DEFAULT_TTL]: " _ttl
  TS_DEFAULT_TTL="${_ttl:-$TS_DEFAULT_TTL}"
fi

validate_zone "$TS_ZONE"
validate_name "TS_SUBDOMAIN" "$TS_SUBDOMAIN"
validate_name "TS_TUNNEL_NAME" "$TS_TUNNEL_NAME"
case "$TS_PORT" in
  ''|*[!0-9]*) ts_die "TS_PORT 须为正整数: $TS_PORT" ;;
esac
case "$TS_DEFAULT_TTL" in
  ''|*[!0-9]*) ts_die "TS_DEFAULT_TTL 须为非负整数: $TS_DEFAULT_TTL" ;;
esac

# --- Write -----------------------------------------------------------------
cat > "$OUT" <<EOF
# tunnel-serve — generated by init-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
TS_ZONE=$TS_ZONE
TS_SUBDOMAIN=$TS_SUBDOMAIN
TS_TUNNEL_NAME=$TS_TUNNEL_NAME
TS_PORT=$TS_PORT
TS_DEFAULT_TTL=$TS_DEFAULT_TTL
EOF

ts_load_config

echo
echo "✓ 已写入 $OUT"
echo "  公网域名: https://${TS_DOMAIN}/<slug>/"
echo
echo "下一步（仅首次）: bash scripts/bootstrap.sh"
